### ISSUE TITLE
export the datasets with missing values

### ISSUE THREAD

**Issue by vrodriguezf** [eXascaleInfolab/bench-vldb20#3]
Hi,

Is there a way to export the datasets with the generated missing values into files?  What command/function should I call if I just want to add the missing data, but not running the algorithms? I want to take them into my own framework to compare my results with those of the benchmark.

Thanks!!

**Comment by mkhayati** [comment]
Hello,

Thanks for the suggestion. We added this functionality to the benchmark. Please have a look at the execution example 5. Please make a pull before running the command. BTW, the benchmark allows adding your own algorithm (C++, Python, or Matlab). This option is described in the extension section.

**Comment by vrodriguezf** [comment]
Thank you so much for your prompt reply & action!!

**Comment by vrodriguezf** [comment]
Sorry to reopen this again, I've tried the command with a single scenario and I've seen that multiple txt files (_m10, ..., _m10) are generated instead of one. What do each of these files represent? 

Thanks!

**Comment by mkhayati** [comment]
No worries at all! Each of those files represents a tick on the x-axis! For example, in the missing % scenario, we vary the missing rate from 10% to 80%! The _m10.txt file is the first tick, i.e., 10% of the data is missing!

**Comment by vrodriguezf** [comment]
oh, I see, thanks again for your reply and your work!
