### ISSUE TITLE
raw results without running the repo?

### ISSUE THREAD

**Issue by juanlopezcode** [eXascaleInfolab/bench-vldb20#6]
Hello, this is not at issue at all, I just wanted to know if is possible that you could share the blackout MAE and RMSE results without need to run the experiments? I will appreciate it. Regards

**Comment by mkhayati** [comment]
Hello, do you still need those results?

**Comment by juanlopezcode** [comment]
hello @mkhayati, unfortunately not anymore, but I appreciate your reply,
